/** Auto-generated — run: npx tsx scripts/fetch-airline-logos.ts */
export const AIRLINE_LOGO_FILES: Record<string, boolean> = {
  "3U": true,
  "9C": true,
  "AA": true,
  "AC": true,
  "AF": true,
  "AI": true,
  "AK": true,
  "AV": true,
  "AY": true,
  "B6": true,
  "BA": true,
  "BR": true,
  "CA": true,
  "CI": true,
  "CM": true,
  "CX": true,
  "CZ": true,
  "DL": true,
  "EI": true,
  "EK": true,
  "ET": true,
  "EY": true,
  "FJ": true,
  "GA": true,
  "GF": true,
  "HA": true,
  "HU": true,
  "HY": true,
  "IB": true,
  "JL": true,
  "KC": true,
  "KE": true,
  "KL": true,
  "LA": true,
  "LH": true,
  "LO": true,
  "LX": true,
  "MF": true,
  "MH": true,
  "MM": true,
  "MS": true,
  "MU": true,
  "NH": true,
  "NX": true,
  "NZ": true,
  "OZ": true,
  "PR": true,
  "QF": true,
  "QR": true,
  "SA": true,
  "SC": true,
  "SK": true,
  "SQ": true,
  "SU": true,
  "SV": true,
  "TG": true,
  "TK": true,
  "TP": true,
  "UA": true,
  "UO": true,
  "VN": true,
  "VS": true,
  "ZH": true,
};

export const ALLIANCE_LOGO_FILES = {
  "star-alliance": "svg",
  skyteam: "png",
  oneworld: "svg",
} as const;

export type AirlineAllianceSlug = keyof typeof ALLIANCE_LOGO_FILES;
