/** Auto-generated — run: node scripts/generate-brand-logo-manifest.mjs */
export const BRAND_LOGO_FILES: Record<string, "svg" | "png"> = {
  "accor": "svg",
  "alila": "svg",
  "aman": "svg",
  "amilla": "png",
  "anantara": "png",
  "andaz": "png",
  "ayada": "png",
  "baglioni": "png",
  "banyan-tree": "svg",
  "baros": "png",
  "belmond": "png",
  "capella": "png",
  "cheval-blanc": "png",
  "como": "png",
  "conrad": "svg",
  "crown-champa": "png",
  "edition": "png",
  "fairmont": "svg",
  "four-seasons": "png",
  "gili": "png",
  "hilton": "png",
  "huvafen": "png",
  "hyatt": "svg",
  "ihg": "svg",
  "intercontinental": "svg",
  "joali": "png",
  "jw-marriott": "png",
  "kempinski": "svg",
  "le-tahaa": "png",
  "likuliku": "png",
  "luxury-collection": "png",
  "lxr": "png",
  "mandarin-oriental": "svg",
  "marriott": "svg",
  "milaidhoo": "png",
  "miraval": "png",
  "nautilus": "png",
  "niyama": "png",
  "north-island": "png",
  "oberoi": "png",
  "one-and-only": "png",
  "park-hyatt": "png",
  "patina": "png",
  "peninsula": "png",
  "qualia": "png",
  "raffles": "png",
  "regent": "png",
  "ritz-carlton": "svg",
  "ritz-carlton-reserve": "png",
  "rosewood": "png",
  "shangri-la": "png",
  "singita": "png",
  "six-senses": "png",
  "sofitel-legend": "png",
  "soneva": "png",
  "st-regis": "svg",
  "test-fs": "png",
  "test-fs2": "png",
  "the-brando": "png",
  "the-datai": "png",
  "vakkaru": "png",
  "velaa": "png",
  "vignette": "png",
  "w-hotels": "svg",
  "waldorf-astoria": "svg",
};

export function getBrandLogoPath(slug: string): string | null {
  const ext = BRAND_LOGO_FILES[slug];
  return ext ? `/brands/${slug}.${ext}` : null;
}
