import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  outputFileTracingRoot: __dirname,
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "media.ffycdn.net" },
      { protocol: "https", hostname: "cdn-assets-eu.frontify.com" },
      { protocol: "https", hostname: "**.fourseasons.com" },
      { protocol: "https", hostname: "**.aman.com" },
      { protocol: "https", hostname: "**.rosewoodhotels.com" },
      { protocol: "https", hostname: "**.chevalblanc.com" },
      { protocol: "https", hostname: "**.mandarinoriental.com" },
      { protocol: "https", hostname: "cache.marriott.com" },
      { protocol: "https", hostname: "digital.ihg.com" },
      { protocol: "https", hostname: "**.hilton.com" },
      { protocol: "https", hostname: "**.hyatt.com" },
      { protocol: "https", hostname: "**.shangri-la.com" },
      { protocol: "https", hostname: "**.peninsula.com" },
      { protocol: "https", hostname: "cdn.sanity.io" },
      { protocol: "https", hostname: "images.squarespace-cdn.com" },
      { protocol: "https", hostname: "**.anantara.com" },
      { protocol: "https", hostname: "**.comohotels.com" },
      { protocol: "https", hostname: "**.belmond.com" },
      { protocol: "https", hostname: "**.sixsenses.com" },
      { protocol: "https", hostname: "**.kempinski.com" },
      { protocol: "https", hostname: "**.accor.com" },
      { protocol: "https", hostname: "m.ahstatic.com" },
      { protocol: "https", hostname: "**.bulgarihotels.com" },
      { protocol: "https", hostname: "**.fairmont.com" },
      { protocol: "https", hostname: "**.raffles.com" },
      { protocol: "https", hostname: "**.sofitel-legend.com" },
      { protocol: "https", hostname: "**.thehousecollective.com" },
      { protocol: "https", hostname: "**.niccolohotels.com" },
      { protocol: "https", hostname: "**.upperhouse.com" },
      { protocol: "https", hostname: "**.ritzcarlton.com" },
      { protocol: "https", hostname: "**.stregis.com" },
      { protocol: "https", hostname: "**.joali.com" },
      { protocol: "https", hostname: "**.soneva.com" },
      { protocol: "https", hostname: "images.kiwi.com" },
      { protocol: "https", hostname: "upload.wikimedia.org" },
    ],
  },
};

export default nextConfig;